"""Original synthetic items. No external calls or proprietary content."""
COURSES=[('Gestão de processos','uma equipe reorganiza seu fluxo de trabalho'),('Educação e aprendizagem','uma equipe docente planeja uma oficina'),('Dados e tecnologia','uma equipe organiza um painel de indicadores'),('Qualidade e comunicação','uma equipe revisa suas práticas de comunicação')]
ITEMS=[
('O grupo identifica atrasos, mas ainda não sabe onde eles ocorrem.','Qual é o primeiro passo para compreender o problema?',['Mapear as etapas e medir os tempos de cada uma.','Contratar uma ferramenta antes de levantar requisitos.','Eliminar todas as reuniões de acompanhamento.','Redefinir a meta sem observar o processo.'],'Mapear o processo e reunir dados permite localizar a causa antes de escolher uma intervenção.','ANALYZE'),
('Um relatório apresenta 80 atividades concluídas de 100 planejadas.','Qual indicador descreve corretamente a execução do plano?',['80% das atividades planejadas foram concluídas.','20% das atividades planejadas foram concluídas.','Foram concluídas 100 atividades.','Todas as atividades tiveram qualidade comprovada.'],'A proporção 80/100 indica 80% de execução, mas não comprova qualidade.','APPLY'),
('Uma nova rotina será testada por duas semanas.','Que prática permite avaliar o teste de forma consistente?',['Definir critérios e uma medida inicial antes do teste.','Escolher os critérios depois de conhecer o resultado.','Considerar apenas a opinião do proponente.','Mudar várias rotinas sem registro.'],'Critérios prévios e uma linha de base permitem comparar o resultado com o objetivo.','EVALUATE'),
('Duas pessoas recebem orientações diferentes para a mesma atividade.','Qual ação reduz novas divergências?',['Manter uma orientação validada, acessível e com responsável definido.','Repassar apenas mensagens individuais sem registro.','Deixar cada pessoa escolher a orientação que ouviu.','Suspender todas as atividades indefinidamente.'],'Uma referência compartilhada facilita consistência e atualização.','UNDERSTAND'),
('A equipe precisa registrar aprendizados ao final de um ciclo.','Qual registro é mais útil para orientar o próximo ciclo?',['Resultado observado, dificuldade e próximo passo acordado.','Uma lista de nomes sem contexto.','Somente uma frase de aprovação geral.','Uma cópia do planejamento sem análise.'],'Um registro acionável relaciona evidências, dificuldades e uma ação futura.','APPLY'),
('Uma planilha contém células vazias em uma variável necessária.','O que fazer antes de interpretar o indicador?',['Investigar os dados ausentes e documentar seu tratamento.','Substituir vazios pelo maior valor observado.','Excluir registros sem avaliar o impacto.','Apresentar o resultado como se a base estivesse completa.'],'Dados ausentes podem alterar a interpretação; o tratamento precisa ser explícito.','ANALYZE'),
('Uma entrega depende da aprovação de outra pessoa.','Qual informação deve estar explícita no acompanhamento?',['Responsável, prazo e condição necessária para aprovação.','Apenas o nome do arquivo final.','Uma data sem responsável.','Somente a quantidade de mensagens.'],'Responsabilidade, prazo e critério de conclusão tornam a dependência verificável.','REMEMBER'),
('Uma proposta de melhoria precisa respeitar recursos limitados.','Qual desenho de piloto favorece uma avaliação útil?',['Escolher um escopo pequeno, definir medidas e revisar resultados.','Aplicar a mudança em todas as áreas sem acompanhamento.','Medir somente quantas pessoas ouviram a proposta.','Adiar o teste até não existir incerteza.'],'Um piloto delimitado permite aprender com resultados observáveis.','CREATE')]

def synthetic_draft(topic,params):
    import hashlib
    row=ITEMS[int(hashlib.sha256(topic.encode()).hexdigest()[:8],16)%len(ITEMS)]
    scenario,stem,answers,rationale,bloom=row
    return {'context':f'Em uma atividade fictícia sobre {topic[:180]}, a equipe discute o seguinte caso: {scenario}','stem':stem,'proposition_two':'','options':[{'text':text,'is_correct':i==0} for i,text in enumerate(answers)],'rationale':rationale+' Rascunho sintético: valide o alinhamento ao objetivo antes de aprovar.','bloom':params.get('bloom') or bloom,'difficulty':params.get('difficulty') or 'MEDIUM','demo':True}
