from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="AcademicTerm",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=40,unique=True)),("active",models.BooleanField(default=True))],options={"ordering":("-name",)}),
        migrations.CreateModel(name="Course",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=180)),("target_count",models.PositiveIntegerField(default=5)),("term",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="courses",to="bank.academicterm"))],options={"ordering":("name",)}),
        migrations.AddConstraint(model_name="course",constraint=models.UniqueConstraint(fields=("term","name"),name="unique_course_term")),
        migrations.CreateModel(name="Question",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("question_type",models.CharField(choices=[("SINGLE","Single answer"),("MULTI","Multiple statements"),("ASSERTION","Assertion–reason")],default="SINGLE",max_length=16)),("context",models.TextField(blank=True)),("stem",models.TextField()),("proposition_two",models.TextField(blank=True)),("rationale",models.TextField()),("bloom",models.CharField(choices=[("REMEMBER","Remember"),("UNDERSTAND","Understand"),("APPLY","Apply"),("ANALYZE","Analyze"),("EVALUATE","Evaluate"),("CREATE","Create")],default="APPLY",max_length=20)),("difficulty",models.CharField(choices=[("EASY","Easy"),("MEDIUM","Medium"),("HARD","Hard")],default="MEDIUM",max_length=12)),("primary_area",models.CharField(blank=True,max_length=120)),("competency",models.CharField(blank=True,max_length=240)),("status",models.CharField(choices=[("PENDING","Pending review"),("APPROVED","Approved"),("REJECTED","Rejected")],default="PENDING",max_length=12)),("review_comment",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("author",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="authored_questions",to=settings.AUTH_USER_MODEL)),("course",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="questions",to="bank.course"))],options={"ordering":("-created_at",)}),
        migrations.CreateModel(name="Option",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("text",models.CharField(max_length=700)),("is_correct",models.BooleanField(default=False)),("order",models.PositiveSmallIntegerField(default=1)),("question",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="options",to="bank.question"))],options={"ordering":("order","id")}),
        migrations.AddConstraint(model_name="option",constraint=models.UniqueConstraint(fields=("question","order"),name="unique_question_option_order")),
        migrations.CreateModel(name="Assessment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=180)),("created_at",models.DateTimeField(auto_now_add=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),("term",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="bank.academicterm"))]),
        migrations.CreateModel(name="AssessmentItem",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("order",models.PositiveIntegerField()),("assessment",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="items",to="bank.assessment")),("question",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="bank.question"))],options={"ordering":("order",)}),
        migrations.AddConstraint(model_name="assessmentitem",constraint=models.UniqueConstraint(fields=("assessment","order"),name="unique_assessment_order")),
        migrations.AddConstraint(model_name="assessmentitem",constraint=models.UniqueConstraint(fields=("assessment","question"),name="unique_assessment_question")),
    ]
