# Generated by Django 5.2.17 on 2026-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bloom',
            field=models.CharField(choices=[('REMEMBER', 'Lembrar'), ('UNDERSTAND', 'Compreender'), ('APPLY', 'Aplicar'), ('ANALYZE', 'Analisar'), ('EVALUATE', 'Avaliar'), ('CREATE', 'Criar')], default='APPLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Média'), ('HARD', 'Difícil')], default='MEDIUM', max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Resposta única'), ('MULTI', 'Múltiplas afirmações'), ('ASSERTION', 'Asserção–razão')], default='SINGLE', max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=12),
        ),
    ]
